### ISSUE TITLE
Freezing GNOME Shell on touchscreen and Wayland

### ISSUE THREAD

**Issue by hyphone** [micheleg/dash-to-dock#1039]
Hello and good day,

when on Wayland and using a touchscreen GNOME Shell usually freezes when touching an Icon in the dock.

The Shell then is not usable anymore, no clicks or keyboard input does something. The window manager still works and I can use my running applications but not interacting with the Shell. 

I reproduced this in Ubuntu 19.04 and 19.10.

I know there is a lack of touchscreen testing but wanted to let you know.

Without Dash to Dock or Ubuntu dock and just the default GNOME Shell Dash it does not freeze.

**Comment by Tooniis** [comment]
I am experiencing this bug as well, although for me keyboard inputs still somewhat work, like pressing alt+f2 to show the command window, and esc to close it.

**Comment by vanderwees** [comment]
I also experience this on Ubuntu 19.10 on Wayland, GNOME Shell 3.34.1.
I am willing to help testing, but would need some hints which files or debug info would be needed.

**Comment by vanderwees** [comment]
I believe #1020 might be related or a duplicate; the situation seems to start with a failed touch, leading into a freeze (feeling) where no touch/click is working as expected anymore.

**Comment by dexterdy** [comment]
I am having the exact same issue with fedora 33 and gnome 3.38.5

**Comment by SilverRoll** [comment]
Reproduced on Manjaro Gnome as well.

**Comment by zoltantamasvajda** [comment]
Same issue, Ubuntu 21.04.

**Comment by Dummyxl** [comment]
also the samen on hp envy and ubuntu 21.04
want to help if needed

**Comment by dumbasPL** [comment]
any progress on this? The issue still exists.
OS: Arch linux

**Comment by Crono23** [comment]
The issue is fixed on Ubuntu 21.10 default dock, are they using a fork of this or is that their own extension?

**Comment by Crono23** [comment]
I just tried testing on Fedora 35, Gnome 41.3 Wayland. It doesn't seem to freeze anymore, can anyone also confirm?

**Comment by StoneToken** [comment]
Hi! Checked on Fedora 35 Wayland on Thinkpad Yoga X1, no ui freezing. I propose resolving this issue.

**Comment by database64128** [comment]
With GNOME 41.3 it's much less likely to freeze, but it can still happen. I just encountered this today for the first time in a month or so when using the touchscreen and mouse at the same time.

**Comment by yavko** [comment]
Happens to me (Manjaro gnome) and my friend (fedora 35 gnome) both on gnome 41

**Comment by vanvugt** [comment]
Confirmed in Ubuntu 20.04.
