### ISSUE TITLE
Strange behaviour on sleep

### ISSUE THREAD

**Issue by xpt1x** [micheleg/dash-to-dock#1185]
`Using ubuntu20.04 LTS`
Extension's latest version is already installed from extensions.gnome.org

If i turn my laptop to sleep, use it again and do a lock screen, suddenly ubuntu's dock starts appearing with dash to dock, which forms 2 docks

I checked with extensions plugin, dash to dock is turning itself off ( maybe similar to this https://github.com/micheleg/dash-to-dock/issues/1180 )
![IMG_20200424_173819](https://user-images.githubusercontent.com/33655587/80211444-639f1900-8653-11ea-9953-9c2808b9e3bc.jpg)
![Screenshot from 2020-04-24 17-38-36](https://user-images.githubusercontent.com/33655587/80211458-6a2d9080-8653-11ea-98d4-be83664368fd.png)

**Comment by warbosstodd** [comment]
I'm seeing the same issue. The only way to correct it is to remove and readd the extension.

**Comment by xpt1x** [comment]
> I'm seeing the same issue. The only way to correct it is to remove and readd the extension.

Yeah, i m just turn on extension or restarting gnome shell

**Comment by xaver13** [comment]
![dash04](https://user-images.githubusercontent.com/15940236/80276034-f1c3df80-86e5-11ea-8e6d-9b9ca50732ab.png)
I have similar problem, I downloaded directly from source.
After display sleep dash to dock extension ended and two docks displayed. 'Dash to dock' dock and dock when dash to dock is not working. Both overlapped. Ubuntu 20.04

**Comment by bheerssen** [comment]
I'm also seeing the same issue with Ubuntu 20.04. Visible dock in the lock screen (with active application indicators, a minor security issue, IMO), and Dash to Dock crashed, but visible along with Ubuntu dock.

**Comment by Ayush-Walia** [comment]
same issue here, getting 2 docks after sleep, though just normally restarting the shell(no need to remove and readd extension), fixes it.

**Comment by matsfjellner** [comment]
Same for me as well, on Ubuntu 20.04, occurs after sleep and Alt+F2 -> r fixes it temporily.

**Comment by rohanmohapatra** [comment]
Is it fixed?

**Comment by syaoo** [comment]
same issue on Ubuntu 20.04
![dock on lockscreen](https://user-images.githubusercontent.com/47080438/80477615-d1fb1880-897e-11ea-9fd3-e1fbe3b969b5.png)
![two docks](https://user-images.githubusercontent.com/47080438/80477642-e212f800-897e-11ea-9925-4182ddae2fbd.png)

**Comment by olson-sean-k** [comment]
I'm running the latest Dash-to-Dock from the extensions website on Arch Linux with GNOME 3.36 and it seems to be causing segfaults in `libst` after sleep. Waking the machine crashes `gnome-shell` and I'm brought back to the `gdm` login screen. Everything appears normal after logging in again.

**Comment by uframer** [comment]
> I'm also seeing the same issue with Ubuntu 20.04. Visible dock in the lock screen (with active application indicators, a minor security issue, IMO), and Dash to Dock crashed, but visible along with Ubuntu dock.

same issue here

**Comment by marto87** [comment]
I think I found a workaround:
Disable ubuntu-dock by renaming the extension directory:

```
cd /usr/share/gnome-shell/extensions/
sudo mv ubuntu-dock@ubuntu.com{,.bak}
```

This way just one instance of dash-to-dock is running, even after locking the session.

Let me know if this works for you too.

**Comment by xpt1x** [comment]
> I think I found a workaround:
> Disable ubuntu-dock by renaming the extension directory:
> 
> ```
> cd /usr/share/gnome-shell/extensions/
> sudo mv ubuntu-dock@ubuntu.com{,.bak}
> ```
> 
> This way just one instance of dash-to-dock is running, even after locking the session.
> 
> Let me know if this works for you too.

Well you can disable it directly no?
With extensions app, we get a option under **Built in** section ..for ubuntu dock, i have already disabled it, but problem is with dash to dock too, sometimes it appears on lock screen too
Just like the first image i shared !

**Comment by marto87** [comment]
What do you mean by "extensions app"? I just know gnome-tweaks and there is no "Built in" section as far as I can see

**Comment by xpt1x** [comment]
Ubuntu now comes with an extensions app, i was talking about that app in my comment, just search for Extensions in dash search if u are running latest ubuntu LTS
Or if u have tweaks installed just scroll down and find `Ubuntu Dock` and disable it

**Comment by alexzorila** [comment]
@xpt1x Hey thanks for mentioning Ubuntu 20.04 "Extensions" App. The fix for me is to disable "Ubuntu Dock" from the "Extensions" App. Using the "Tweaks" app to disable "Ubuntu Dock" does not fix the issue.

**Comment by xpt1x** [comment]
@alexzorila make sure its disabled in both 'Extensions' app and 'Tweaks' app, i myself tried it again by enabling ubuntu dock in extensions app and issue appeared again, so i again turned it off from both apps and its again gone now !
This fix is perfectly working for me and others too, i havent seen it within last days

**Comment by johnmee** [comment]
This journal entry seems relevant...

```
May 03 10:35:02 bigbox gnome-shell[2407]: JS ERROR: Error: Argument 'instance' (type interface) may not be null
                                          _init/GObject.Object.prototype.disconnect@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:571:24
                                          _remove@/home/john/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js:104:18
                                          removeWithLabel@/home/john/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js:52:22
                                          _restoreDash@/home/john/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1829:30
                                          _toggle/this._toggleLater<@/home/john/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1651:18
May 03 10:35:02 bigbox gnome-shell[2407]: #4   55b6d26d1818 i   /home/john/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1651 (377ac4a0088 @ 23)
May 03 10:35:02 bigbox gnome-shell[2407]: #3   55b6d26d18a8 i   /home/john/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1829 (377ac4a05b0 @ 133)
May 03 10:35:02 bigbox gnome-shell[2407]: #2   55b6d26d1970 i   /home/john/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js:52 (377ac4a0d30 @ 81)
May 03 10:35:02 bigbox gnome-shell[2407]: #1   55b6d26d1a18 i   /home/john/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js:104 (377ac4a0f10 @ 17)
May 03 10:35:02 bigbox gnome-shell[2407]: #0   7ffedf794220 b   resource:///org/gnome/gjs/modules/core/overrides/GObject.js:571 (32e2cbeb6c40 @ 25)
May 03 10:35:02 bigbox gnome-shell[2407]: == Stack trace for context 0x55b6d06eb6e0 ==
May 03 10:35:02 bigbox gnome-shell[2407]: Object .Gjs_ubuntu-dock_ubuntu_com_dash_DashToDock_MyDash (0x55b6d14d9060), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
```
Trying to talk to an object which has been garbage collected??

**Comment by conualfy** [comment]
I experienced the dock in the locked screen, too. Ubuntu 20.04, just like it was in the previous editions of Ubuntu. I know it is Gnome Shell bug to allow anything visible in the lock screen, but still, should be fixed in a more permanent way.

**Comment by bheerssen** [comment]
I installed vanilla gnome to see if it helps, and it doesn't, really. There's no Ubuntu dock, obviously, so now I don't get overlapping docks when I unlock the session. However, I still sometimes see the Dash-to-Dock in the lock screen.

**Comment by KontactoServicios** [comment]
I had the same condition, reading your post I take in accounta I had installed an app name extensions (manage GNOME extension) also tweaks, I do not remember why I got both.
The point is after removing extension, the problem disapears, I tested and do not fail againg.
I hope it can be helpfull.

**Comment by 4AHZ** [comment]
I disabled "Ubuntu Dock" both in "Extension" and "Tweaks" but the issue is not fixed.

**Comment by qtsound** [comment]
cd /usr/share/gnome-shell/extensions/
sudo mv ubuntu-dock@ubuntu.com{,.bak}

Works for me. Ubuntu 20.04.
Thanks!

**Comment by jcasfer83** [comment]
Hi I do have that proble with the icons... but I have asociated those also:
1. in first suspension (sleep) the screen becomes dark.
2. in second suspension happened the staf with the icons (now its not happening because y introduced the comads bellow).
3. in thirth suspensión icons and top bar desapears and letters on switch off menu desaperars...
Any help please?
![PrimeraSuspension](https://user-images.githubusercontent.com/71668382/100368814-5a6c9500-3004-11eb-963f-55e5ca486d95.jpg)
![FondoVacio](https://user-images.githubusercontent.com/71668382/100368857-65272a00-3004-11eb-87c2-f13087dbe556.jpg)
![MenuApagar](https://user-images.githubusercontent.com/71668382/100368874-69534780-3004-11eb-9422-3d60d1d9910f.jpg)

**Comment by Nakkhatra** [comment]
> I think I found a workaround: Disable ubuntu-dock by renaming the extension directory:
> 
> ```
> cd /usr/share/gnome-shell/extensions/
> sudo mv ubuntu-dock@ubuntu.com{,.bak}
> ```
> 
> This way just one instance of dash-to-dock is running, even after locking the session.
> 
> Let me know if this works for you too.

Hi, it didn't work for me. How can I revert this setting back?

**Comment by rela589n** [comment]
Is anybody facing the same problem on Wayland?

**Comment by erfanium** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/2f09e78e-26f3-445b-93e6-72cb4b7fe589" />


sometimes this happens after suspend. ubuntu 25.04
