### ISSUE TITLE
Scrolling not working at all

### ISSUE THREAD

**Issue by PleaseConverge** [micheleg/dash-to-dock#2032]
The v82 update broke something and scrolling is no longer registered at all, anywhere. This includes:
- scrolling over the "Show applications" button or any empty part of the dock to switch workspace
- scrolling the dock to see other icons with 'Fixed icon size' enabled
- scroll over an icon with 'Scroll action→Cycle through windows' enabled.

The problem persists whatever the combination of enabling/disabling 'Fixed icon size' and any 'Scroll action' setting.

Ubuntu 22.04.2
GNOME 42.5 (X11)

**Comment by sirazsk** [comment]
I am also having same issues 

I used to use cycle through windows using scroll, after this update this broke.
can anyone tell me how i can install older version of the extention

Ubunutu 22.04.1
GNOME 42.5 (WAYLAND)

**Comment by 3v1n0** [comment]
Mh, I can't reproduce this locally, it seems related to some parameter...

However, is it also happening in wayland from what I see, right?

**Comment by 3v1n0** [comment]
I've released a new version but it should not fix this this, unless I'm missing something, however it would be nice if you could provide a `git bisect` to figure out what was the guilty commit.

**Comment by 3v1n0** [comment]
Maybe https://github.com/micheleg/dash-to-dock/commit/c6c4092d9134b718a940a168ce06dac92710f779 is related?

**Comment by 3v1n0** [comment]
It seems https://github.com/micheleg/dash-to-dock/pull/2040 helps here too

**Comment by PleaseConverge** [comment]
Just installed v83, as expected it didn't fix anything.

Manually commenting line 448 in `docking.js` as per https://github.com/micheleg/dash-to-dock/pull/2040 did the trick though! Thanks!
