### ISSUE TITLE
screen gap & overlapping Dock (in Panel mode) when GNOME panel at bottom of screen

### ISSUE THREAD

**Issue by user501254** [micheleg/dash-to-dock#230]
So it is quite obvious that the panel mode in the extension assumes that GNOME (top) panel is situated at the top of the screen, which is its default position.

However I belong to a group of people who like it at the bottom (see screenshot). This makes the Docked panel overlap with the GNOME panel and also leaves a gap at the top, presumably equal to the height of the GNOME panel if it was there. ![screenshot from 2015-10-04 17-44-43](https://cloud.githubusercontent.com/assets/6129517/10267764/be2a77ac-6abf-11e5-8160-a5f254898dc4.png)

**I was wondering if the panel mode could be implemented in a more dynamic way that takes into account the position of the panel so that it doesn't overlap and/or leave gaps.**

BTW, I am using [MMOD Panel](https://extensions.gnome.org/extension/898/mmod-panel/) extension to move the GNOME Panel to the bottom of the screen.

**Comment by micheleg** [comment]
It should be fixed in current master now [58164378d267272f3107a3ca59792fb935840da5]. Can you try it?

**Comment by user501254** [comment]
I tried the current master branch but couldn't get the extension to work, probably because I am still stuck with GNOME Shell 3.16.3.
Changing the `shell-version` in `metadata.json` also din't work. 

Fedora will be getting 3.18 next month I could try it then and let you know if you are okay with it.

**Comment by user501254** [comment]
okay I gave it another try by just replacing the contents of `dockedDash.js` file. The issue is solved. 
Great job :+1:

**Comment by micheleg** [comment]
Just updated the gnome-3.16 and 3.14 branches as well.

**Comment by gdenat** [comment]
Hello,
I'm facing the very same issue, using Gnome 3.18.
I tried to update the extension to the master branch of the git repo without any improvement.
I'm using the BottomPanel extension to move the panel (https://extensions.gnome.org/extension/949/bottompanel/), but the issue is still the same with MMOD Panel.

**Comment by micheleg** [comment]
Hi, do you have a multi-monitor configuration?

**Comment by gdenat** [comment]
Nope, only one monitor (it's a laptop).

**Comment by micheleg** [comment]
Can you confirm you are running the latest master version and that you restarted the shell?

**Comment by gdenat** [comment]
That was the problem... I was disabling the extension, removing ~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/, installing the master version, and enabling the extension again. It seems that it is not sufficent to take the new files into account.

To be sure, I have rebooted the machine after installing the new version, and the issue is solved. Thanks for your help and for the development of this great extension!
