### ISSUE TITLE
Use higher quality image scaling i.e for previews

### ISSUE THREAD

**Issue by bjornharrtell** [micheleg/dash-to-dock#2401]
dash-to-dock scaling preview:

![Image](https://github.com/user-attachments/assets/f12a6cd4-1d83-435a-8804-48e73011efa2)

Cubic interpolation:

![Image](https://github.com/user-attachments/assets/4e2b33a7-20d4-4ca0-9e13-2f32a5bbba6d)

This comparison doesn't do cubic justice, GitHub is compressing assets so that it becomes blurry. In reality it looks much better and sharper and alot better than what dash-to-dock is using.

Bilinear also seem to produce similar quality.

It looks like dash-to-dock scaling is without interpolation.

**Comment by vanvugt** [comment]
The scaling method has changed over the years but the implementation lives in gnome-shell. So this probably isn't a dash-to-dock bug. What version of gnome-shell are you using?

**Comment by bjornharrtell** [comment]
I'm at gnome-shell 42.1 on Ubuntu 24.0.4. Tried to hack a bit in the code and look up clutter / mutter API but unable to figure it out as of yet. (I am also unable to figure out how to develop / debug / find correct API to use other than complete trial and error in the dark.. I must be missing some knowledge here).

The scaling that gnome-shell does itself when when zooming out to workspace windows overview do seem interpolated and better:

![Image](https://github.com/user-attachments/assets/3860b818-c508-4bc6-9232-d7e9fbf4a78b)

vs.

![Image](https://github.com/user-attachments/assets/476c592f-8cc3-44de-a698-53cdd0d744d2)

**Comment by vanvugt** [comment]
gnome-shell 42.1 does not exist in any version of Ubuntu. Can you check your versions again?

Or maybe don't bother, because I suspect you use Ubuntu 22.04 and gnome-shell 42.x. As such you'd be missing https://gitlab.gnome.org/GNOME/mutter/-/commit/16fa2100dcb31b911a029a93e350c77c3944c262 (fixed in Mutter 43.0) and related changes. So I think this bug was already fixed years ago.

Please try Ubuntu 24.04 instead: https://ubuntu.com/download/desktop

**Comment by vanvugt** [comment]
Closing: This is very likely fixed already in newer GNOME versions. And even if it's not, it's not dash-to-dock's responsibility.

**Comment by bjornharrtell** [comment]
Hmm I see, thanks for investigating @vanvugt.

However I now see I looked up the wrong package and version. I'm at Ubuntu 24.04.2 and the gnome-shell package is 46.0, so unfortunately it seems it's not fixed?

**Comment by vanvugt** [comment]
OK, that's interesting. What you should do next is:
1. [Report it to Ubuntu](https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+filebug) with a screenshot and include software versions.
2. If you are willing to test Ubuntu 25.04 and can confirm it's still a problem there, then it should also be [reported upstream](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues) as a bug in GNOME 48.

**Comment by vanvugt** [comment]
Oh no. I think I was completely wrong in assuming dash-to-dock inherited gnome-shell's preview code. It seems to have its own implementation, so will have its own bugs ☹

**Comment by bjornharrtell** [comment]
Ah yes that seems to align with what I've looked at when attempting (and failing) to hack in https://github.com/micheleg/dash-to-dock/blob/master/windowPreview.js. :)
