### ISSUE TITLE
Please roll up a new release for gnome 3.32.0

### ISSUE THREAD

**Issue by mrkz** [micheleg/dash-to-dock#907]
Hello, I've tested latest release of dash-to-dock (v65) with new gnome 3.32.0 on Clearlinux, failing with the following:
```
Mar 13 11:19:52 mark-pc gnome-shell[1141]: loading user theme: /usr/share/themes/Arc-Dark/gnome-shell/gnome-shell.css
Mar 13 11:19:52 mark-pc gnome-shell[1141]: JS ERROR: TypeError: this._construct is not a function
                                                                newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
                                                                _createAppItem@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js:441:23
                                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                                _redisplay@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js:788:31
                                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                                updateCustomTheme@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:221:9
                                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                                loadTheme@resource:///org/gnome/shell/ui/main.js:349:5
                                                                _changeTheme@/usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com/extension.js:56:9
                                                                enable@/usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com/extension.js:19:9
                                                                enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:131:9
                                                                loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:177:17
                                                                _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:324:9
                                                                _emit@resource:///org/gnome/gjs/modules/signals.js:142:27
                                                                _loadExtension@resource:///org/gnome/shell/misc/extensionUtils.js:244:9
                                                                scanExtensions/<@resource:///org/gnome/shell/misc/extensionUtils.js:250:13
                                                                collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:25:17
                                                                scanExtensions@resource:///org/gnome/shell/misc/extensionUtils.js:249:9
                                                                _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:326:5
                                                                enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:334:9
                                                                _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:365:9
                                                                init@resource:///org/gnome/shell/ui/extensionSystem.js:373:5
                                                                _initializeUI@resource:///org/gnome/shell/ui/main.js:222:5
                                                                start@resource:///org/gnome/shell/ui/main.js:124:5
                                                                @<main>:1:31
Mar 13 11:19:52 mark-pc gnome-shell[1141]: length values must specify a unit
Mar 13 11:19:52 mark-pc gnome-shell[1141]: length values must specify a unit
Mar 13 11:19:52 mark-pc gnome-shell[1141]: Ignoring length property that isn't a number at line 753, col 24
Mar 13 11:19:53 mark-pc NetworkManager[1304]: <info>  [1552497593.0205] agent-manager: req[0xe161f0, :1.1048/org.gnome.Shell.NetworkAgent/1000]: agent registered
Mar 13 11:19:53 mark-pc gnome-shell[1141]: JS ERROR: TypeError: this._construct is not a function
                                                                newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
                                                                _createAppItem@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js:441:23
                                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                                _redisplay@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js:788:31
                                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                                _runDeferredWork@resource:///org/gnome/shell/ui/main.js:593:5
                                                                _runBeforeRedrawQueue@resource:///org/gnome/shell/ui/main.js:608:9
                                                                _queueBeforeRedraw/<@resource:///org/gnome/shell/ui/main.js:617:13
Mar 13 11:19:53 mark-pc gnome-shell[1141]: JS ERROR: TypeError: this._construct is not a function
                                                                newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
                                                                _createAppItem@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js:441:23
                                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                                _redisplay@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js:788:31
                                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                                updateCustomTheme@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:221:9
                                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                                _initialize@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:419:9
                                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22

```
but using master branch as is now (commit ee917cd842a56449cb712ed5155185e2a715ea87) works correctly, so please consider tagging a new release for the gnome 3.32.0 release (which went out Mar 11: https://download.gnome.org/sources/gnome-shell/3.32/). 

Thanks!

**Comment by elgs** [comment]
Please please please!

**Comment by Galaxy0419** [comment]
Have some issues on Arch Linux, too. The current version seems not compatible with 3.32. 
**ISSUES:**
1. I can't remove favorite apps from the dock (Even switch back to default which made me wonder if it breaks default settings).
2. No favorite apps can be shown on the dock.
**System Info:**
OS: Arch Linux (fully upgraded 2019-3-16)
Extension Version: 65-1

**Comment by vageliskatsiotis** [comment]
Hi. Similar issue with loading extension. Recently updated and extension throws error in https://extensions.gnome.org/local/. 
OS: Antergos
Kernel: x86_64 Linux 4.19.29-1-lts
Gnome-Shell: 3.32.0-1

**Comment by michaelothing** [comment]
Same issue with Gnome Shell 3.32.0-1. Extension not loading.
Antergos 
Kernel 5.0.2-arch1-1-ARCH

**Comment by x80486** [comment]
...much needed! Please, do roll up a release :innocent:

**Comment by rockon999** [comment]
The branch es6 works!

**Comment by Galaxy0419** [comment]
If you are using arch-based linux, make sure your system are fully upgrded and install git version from aur. It works for me now.

**Comment by elgs** [comment]
@Galaxy0419 which aur package exactly?

**Comment by AlexWayfer** [comment]
@elgs I think, @Galaxy0419 is talking about https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-dock-git/

**Comment by Galaxy0419** [comment]
Exactly

**Comment by elgs** [comment]
Thanks but the last update was in 2017?

**Comment by Galaxy0419** [comment]
> Thanks but the last update was in 2017?

Yeah, the script was out-of-date, but it use the source code of github to build.

**Comment by Galaxy0419** [comment]
The incompatibility may be related to [this](https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/361) change. If you want to build yourself you can use es6 branch.

**Comment by jasondaigo** [comment]
> @elgs I think, @Galaxy0419 is talking about https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-dock-git/

that version is also not loading with current gnome-shell for me

**Comment by MaxXor** [comment]
Please update.

**Comment by elgs** [comment]
Thanks! But just out of curiosity, if I install the last update in 2017 package from aur, does it mean I would not receive any update from aur since 2017 because the aur package is not updated? How would the aur package user update this package? Thanks.

**Comment by jasondaigo** [comment]
> Thanks! But just out of curiosity, if I installed the last update in 2017 package from aur, does it mean I would not receive any update from aur since 2017 because the aur package is not updated? How would the aur package users update this package? I mean if I install the aur package today, and if the author of this aur package would not do anything in the future, this aur package in my computer would never get any update, is it correct? Thanks.

usually if a aur package contains github sources it gets updated fine. exceptions exists.

**Comment by elgs** [comment]
@jasondaigo, I use yay, so does it mean each time when I do `yay -Syu`, it actually goes all the way to the Github to check if there's any new versions? Previously I thought only the aur package author's update will triger a `yay` update.

**Comment by jasondaigo** [comment]
Im not sure but i think you have to rebuild it yourself from time to time cause no change in the package

**Comment by elgs** [comment]
@jasondaigo, thanks!

**Comment by sidbmw** [comment]
Just updated gnome on unstable branch Manjaro and it throws this...

GLib.FileError: Failed to open file “/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/gschemas.compiled”: open() failed: No such file or directory

Stack trace:
  getSettings@resource:///org/gnome/shell/misc/extensionUtils.js:114:24
  DashToDock_Settings@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:87:26
  buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:857:20
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:75:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:320:17
  main@resource:///org/gnome/shell/extensionPrefs/main.js:635:5
  @<main>:1:43

**Comment by micheleg** [comment]
I have released v66 here https://micheleg.github.io/dash-to-dock/release/2019/03/17/new-release-v66-gnome-3.32-support.html and https://github.com/micheleg/dash-to-dock/releases/tag/extensions.gnome.org-v66. If you are already on 3.32 most likely you'll need to manually install this version, as the ones available on the extension website and most distributions are most likely outdated.

**Comment by drakkan** [comment]
for Arch users, stable aur packages updated

https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-dock/

no more need to use the git version

**Comment by vageliskatsiotis** [comment]
Thanx guys for the good work!

**Comment by pascalduez** [comment]
>  If you are already on 3.32 most likely you'll need to manually install this version, as the ones available on the extension website and most distributions are most likely outdated.

For the extensions website, is it just a matter of time to get it updated there, or managing extensions through it is deprecated or something?

**Comment by Tids** [comment]
v66 now, but still cant load the extension on Gnome 3.32. The only things i can find in the log is:
```
dash-to-dock_micxgx.gmail.com has error: TypeError: Shell.GenericContainer is not a constructor
Extension "dash-to-dock@micxgx.gmail.com" had error: TypeError: Shell.GenericContainer is not a constructor
```

**Comment by micheleg** [comment]
@Tids you are somhow still running an older versio as Shell.GenericContainer is not any more used in v66.
